## **Pandas Fundamentals**

Pandas is one of the most important Python libraries for Data Analysis and Data Science.

It provides powerful and flexible data structures, especially Series and DataFrame, for working with structured data.

In this notebook, we will learn how to create, load, inspect, select, filter, analyze, modify, combine, and export data using Pandas.

**Learning Objectives**

`By the end of this notebook, you will be able to:`

1. Import Pandas

2. Pandas Series
   2.1 Creating a Series
   2.2 Series Index
   2.3 Accessing Series Values
   2.4 Series Attributes

3. Pandas DataFrame
   3.1 Creating a DataFrame from a Dictionary
   3.2 Creating a DataFrame from a NumPy Array

4. Loading Data
   4.1 Reading a CSV File

5. Exploring and Inspecting Data
   5.1 head()
   5.2 tail()
   5.3 sample()
   5.4 shape
   5.4 dtypes
   5.5 info()

6. Selecting Data
   6.1 Single Column
   6.2 Multiple Columns
   6.3 Rows
   6.4 loc[]
   6.5 iloc[]

7. Filtering and Sorting Data
   7.1 Filtering
       Single Condition
       Specific Columns
       Multiple Conditions
       isin()
   7.2 Sorting

8. Rename Columns

9. Adding and Modifying Columns

10. Basic Data Analysis
    10.1 count()
    10.2 sum()
    10.3 mean()
    10.4 median()
    10.5 min()
    10.6 max()
    10.7 describe()

11. Unique Values and Frequency Analysis
    11.1 unique()
    11.2 nunique()
    11.3 value_counts()

12. Grouping and Aggregation
    12.1 groupby()
    12.2 agg()

13. Working with Text Data
    13.1 upper()
    13.2 lower()
    13.3 strip()

14. Exporting Data
    14.1 to_csv()

15. Practical Data Analysis Example

16. Summary

#### **1. Import Pandas**

Pandas is conventionally imported using the alias `pd`.

This allows us to use Pandas functions with the shorter `pd` prefix.

In [64]:
import pandas as pd

#### **2. Loading Data**

##### **Reading a CSV File**

CSV (Comma-Separated Values) is one of the most common formats used in Data Analysis.

In [65]:

# Load the dataset
df = pd.read_csv("../datasets/raw/ITAR_Student_Performance_Dataset_v1.0.csv")
# pd.read_excel("abc.xlsx")
# pd.read_json("data.json")

#### **3. Pandas Series**

A Pandas Series is a one-dimensional labeled data structure.

It can be thought of as a single column of data with an associated index.

#### **3.1 Creating a Series**

In [66]:
marks = pd.Series([75, 82, 68, 91, 88])

marks

0    75
1    82
2    68
3    91
4    88
dtype: int64

#### **3.2 Series Index**

In [67]:
marks.index

RangeIndex(start=0, stop=5, step=1)

#### **3.3 Accessing Series Values**

In [68]:
marks[0]

np.int64(75)

#### **3.4 Series Attributes**

In [69]:
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data Type:", marks.dtype)

Shape: (5,)
Size: 5
Data Type: int64

#### **4. Pandas DataFrame**

A DataFrame is a two-dimensional labeled data structure consisting of rows and columns.

It is the primary Pandas structure used for tabular data analysis.

#### **4.1 Creating a DataFrame from a Dictionary**

In [70]:
student_data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Marks": [85, 78, 92],
    "Department": ["CS", "AI", "CS"]
}

students = pd.DataFrame(student_data)

students

    Name  Marks Department
0    Ali     85         CS
1  Ahmed     78         AI
2   Sara     92         CS

#### **4.2 Creating a DataFrame from a NumPy Array**

In [71]:
import numpy as np

# Create a 2D NumPy array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])

# Convert to DataFrame
numpy_data = pd.DataFrame(array_2d)
print(numpy_data)

    0   1   2
0  10  20  30
1  40  50  60

In [72]:
# Define custom column and row labels
column_names = ['Price', 'Quantity', 'Rating']
row_ids = ['Store_A', 'Store_B']

# Create DataFrame with labels
df_labeled = pd.DataFrame(array_2d, columns=column_names, index=row_ids)
print(df_labeled)

         Price  Quantity  Rating
Store_A     10        20      30
Store_B     40        50      60

#### **5. Exploring and Inspecting Data**

##### **5.1 head()**

The `head()` method returns the first five rows of a DataFrame by default.

It is useful for quickly previewing a dataset.

In [73]:
df.head()
# df.head(2)

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0

##### **5.2 tail()**

The `tail()` method returns the last five rows by default.

In [74]:
df.tail()
# df.tail(8)

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,30000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

##### **5.3 sample()**

The `sample()` method returns randomly selected rows from the DataFrame.

In [75]:
df.sample(4)

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,30000.0
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,25000.0
122,2024123,Usaid Ali,Male,20,DS,3,91,88.8,Peshawar,9/3/2024,usaid.ali2024123@usaid.ali2024123@itar.edu.pk,No,30000.0
40,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,30000.0

##### **5.4 shape**

Returns the number of rows and columns.

In [76]:
df.shape

(150, 13)

##### **5.5 Data Types**

its show the data type of each column

In [77]:
df.dtypes

student_id                 int64
full_name                    str
gender                       str
age                          str
department                   str
semester                   int64
marks                        str
attendance_percentage    float64
city                         str
admission_date               str
email                        str
scholarship                  str
tuition_fee              float64
dtype: object

##### **5.6 info()**

The `info()` method provides a concise summary of the DataFrame, including:

- Number of rows
- Column names
- Number of non-null values
- Data types
- Memory usage

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             150 non-null    int64
 1   full_name              150 non-null    str
 2   gender                 148 non-null    str
 3   age                    147 non-null    str
 4   department             150 non-null    str
 5   semester               150 non-null    int64
 6   marks                  142 non-null    str
 7   attendance_percentage  104 non-null    float64
 8   city                   150 non-null    str
 9   admission_date         148 non-null    str
 10  email                  145 non-null    str
 11  scholarship            149 non-null    str
 12  tuition_fee            147 non-null    float64
dtypes: float64(2), int64(2), str(9)
memory usage: 15.4 KB

#### **6. Selecting Data**

##### **6.1 Selecting a Single Column**

In [79]:
# Display Single Column Data
df["marks"]

0       67
1       77
2       70
3       71
4       82
      ...
145     70
146     80
147    105
148    -10
149    NaN
Name: marks, Length: 150, dtype: str

##### **6.2 Selecting Multiple Columns**

In [80]:
# Select Multiple Columns
df[["full_name", "department", "marks"]]

          full_name department marks
0     Muhammad Khan         SE    67
1          Ali Khan         DS    77
2        Ahmad Khan         CS    70
3        Hamza Khan         DS    71
4     Abdullah Khan         AI    82
..              ...        ...   ...
145      Ahmad Khan         CS    70
146  Muhammad Ahmad         IT    80
147       Ali Ahmad         AI   105
148     Ahmad Ahmad         IT   -10
149     Naveed Khan         CS   NaN

[150 rows x 3 columns]

##### **6.3 Selecting Rows**

In [81]:
# Select Multiple Rows
df[1:5]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0

##### **6.4 loc[] vs iloc[]**

| Method | Selection Method | Example |
|---|---|---|
| `loc[]` | Label-based | `df.loc[0, "marks"]` |
| `iloc[]` | Position-based | `df.iloc[0, 2]` |

##### Important Difference

- `loc[]` uses row/column labels.
- `iloc[]` uses integer positions.
- `loc[]` includes the ending label in a slice.
- `iloc[]` follows standard Python slicing and excludes the ending position.

##### **Selecting Data Using loc[]**

In [82]:
# Select Single Row
df.loc[5]

student_id                                      2024006
full_name                                   Hassan Khan
gender                                              NaN
age                                                  -5
department                                           CS
semester                                              5
marks                                                95
attendance_percentage                              93.4
city                                           Peshawar
admission_date                                 8/3/2024
email                    hassan.khan2024006@itar.edu.pk
scholarship                                         Yes
tuition_fee                                     15000.0
Name: 5, dtype: object

In [83]:
# Select Multiple Rows
df.loc[5:10]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,15000.0
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,NaN
7,2024008,Fatima Khan,Female,23,SE,6,70,85.2,Kohat,NaN,fatima.khan2024008@itar.edu.pk,No,30000.0
8,2024009,Usman Khan,Male,22,AI,6,68,64.4,Peshawar,2/23/2024,NaN,No,30000.0
9,2024010,Awais Khan,Male,19,IT,1,79,NaN,Islamabad,12/13/2024,awais.khan2024010@itar.edu.pk,No,50000.0
10,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0

In [84]:
# Select Multiple Rows and Specific Columns
# df.loc[0:5,"marks"]
df.loc[0:5, ["full_name", "marks"]]

       full_name marks
0  Muhammad Khan    67
1       Ali Khan    77
2     Ahmad Khan    70
3     Hamza Khan    71
4  Abdullah Khan    82
5    Hassan Khan    95

##### **Selecting Data Using iloc[]**

In [85]:
# Select 1st Row
df.iloc[3]

student_id                                     2024004
full_name                                   Hamza Khan
gender                                            Male
age                                                 19
department                                          DS
semester                                             2
marks                                               71
attendance_percentage                             85.2
city                                             Bannu
admission_date                              20-03-2024
email                    hamza.khan2024004@itar.edu.pk
scholarship                                         No
tuition_fee                                    30000.0
Name: 3, dtype: object

In [86]:
# Select 1st five rows
df.iloc[0:5]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0

In [87]:
# Display first five rows and the first four columns. 
df.iloc[0:5, 0:4]

   student_id      full_name gender age
0     2024001  Muhammad Khan   Male  20
1     2024002       Ali Khan   Male  23
2     2024003     Ahmad Khan   Male  18
3     2024004     Hamza Khan   Male  19
4     2024005  Abdullah Khan   Male  18

#### **7. Filtering and Sorting Data**

##### **7.1 Filtering**

##### **Filtering with a Single Condition**

In [88]:
# Select students whose Attendance Percentage are greater than 80.
df[df["attendance_percentage"] > 80]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,15000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,25000.0
141,2024142,Rehan Ali,Male,19,DS,3,84,82.1,Peshawar,10/11/2024,rehan.ali2024142@rehan.ali2024142@itar.edu.pk,Yes,15000.0
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000.0
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

In [89]:
 # Select Students who study in CS Department 
df[df["department"] == "CS"]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,15000.0
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000.0
16,2024017,Asad Khan,Male,NaN,CS,4,absent,NaN,Kohat,11/22/2024,asad.khan2024017@itar.edu.pk,No,30000.0
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000.0
20,2024021,Yasir Khan,Male,18,CS,2,82,93.7,Kohat,2/12/2024,yasir.khan2024021@yasir.khan2024021@itar.edu.pk,Yes,15000.0
22,2024023,Shahzaib Khan,Male,19,CS,3,74,81.8,Mardan,11/22/2024,shahzaib.khan2024023@shahzaib.khan2024023@itar...,No,30000.0
24,2024025,Rizwan Khan,Male,22,CS,4,46,52.9,Dera Ismail Khan,4/12/2024,rizwan.khan2024025@rizwan.khan2024025@itar.edu.pk,Yes,15000.0
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,25000.0
34,2024035,Areeba Khan,Female,24,CS,6,73,83.9,Quetta,12/4/2024,areeba.khan2024035@areeba.khan2024035@itar.edu.pk,No,30000.0
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000.0
43,2024044,Anum Khan,Female,24,CS,6,86,91.9,Swat,11/19/2024,anum.khan2024044,Yes,15000.0
51,2024052,Maham Khan,Female,22,CS,4,73,86.4,Swat,8/15/2024,maham.khan2024052@maham.khan2024052@itar.edu.pk,Yes,15000.0
53,2024054,Bushra Khan,Female,25,CS,7,90,88.2,Karachi,10/28/2024,bushra.khan2024054@bushra.khan2024054@itar.edu.pk,No,30000.0
55,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0
56,2024057,Nimra Khan,Female,20,CS,3,87,94.2,Swat,7/1/2024,nimra.khan2024057,Yes,15000.0
64,2024065,Rameez Khan,Male,20,CS,3,89,94.2,Islamabad,2/2/2024,rameez.khan2024065@rameez.khan2024065@itar.edu.pk,Yes,15000.0
74,2024075,Ahmad Ali,Male,20,CS,2,84,NaN,Peshawar,12/23/2024,ahmad.ali2024075@ahmad.ali2024075@itar.edu.pk,No,30000.0
77,2024078,Amna Khan,Female,22,CS,4,NaN,88.8,Lahore,3/23/2024,amna.khan2024078@amna.khan2024078@itar.edu.pk,No,30000.0
78,2024079,Hoorain Khan,Female,19,CS,2,75,NaN,Peshawar,10/28/2024,hoorain.khan2024079@hoorain.khan2024079@itar.e...,No,30000.0
94,2024095,Fatima Bibi,F,22,CS,6,80,91.4,Peshawar,3/6/2024,fatima.bibi2024095@fatima.bibi2024095@itar.edu.pk,No,30000.0
104,2024105,Sohail Ali,Male,21,CS,3,89,84.8,Karachi,15/03/2024,sohail.ali2024105@sohail.ali2024105@itar.edu.pk,No,30000.0
106,2024107,Iqra Bibi,Female,19,CS,1,83,105.0,Quetta,3/29/2024,iqra.bibi2024107@iqra.bibi2024107@itar.edu.pk,No,50000.0
109,2024110,Sana Bibi,Female,19,CS,3,96,91.1,Peshawar,2/17/2024,sana.bibi2024110@sana.bibi2024110@itar.edu.pk,Yes,15000.0
114,2024115,Waqar Ali,Male,23,CS,5,81,NaN,Mardan,4/8/2024,waqar.ali2024115,No,30000.0
116,2024117,Irfan Ali,Male,23,CS,7,54,63.6,Mardan,6/2/2024,irfan.ali2024117,No,30000.0
117,2024118,Noor Bibi,Female,23,CS,6,94,92.9,Dera Ismail Khan,6/13/2024,noor.bibi2024118@noor.bibi2024118@itar.edu.pk,Yes,15000.0
119,2024120,Sameer Ali,Male,20,CS,2,61,65.0,Mardan,10/16/2024,sameer.ali2024120@sameer.ali2024120@itar.edu.pk,No,30000.0
120,2024121,Sidra Bibi,Female,18,CS,1,84,89.7,Mardan,3/28/2024,sidra.bibi2024121,No,50000.0
127,2024128,Mehwish Bibi,Female,23,CS,5,70,81.9,Dera Ismail Khan,9/20/2024,mehwish.bibi2024128,No,30000.0
131,2024132,Kainat Bibi,Female,19,CS,2,73,NaN,Quetta,6/8/2024,kainat.bibi2024132@kainat.bibi2024132@itar.edu.pk,No,30000.0
136,2024137,Farhan Ali,Male,22,CS,4,-10,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,15000.0
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000.0
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,25000.0
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

In [90]:
# Select Students who belong to Bannu City
df[df["city"] == "Bannu"]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
13,2024014,Fahad Khan,Male,18,SE,1,86,82.8,Bannu,3/3/2024,fahad.khan2024014@itar.edu.pk,No,50000.0
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000.0
17,2024018,Maryam Khan,NaN,22,DS,4,69,84.6,Bannu,2/27/2024,NaN,No,30000.0
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000.0
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
29,2024030,Kashif Khan,Male,21,SE,4,76,90.5,Bannu,11/25/2024,kashif.khan2024030@kashif.khan2024030@itar.edu.pk,No,30000.0
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,25000.0
36,2024037,Sidra Khan,Female,23,SE,5,86,82.2,Bannu,12/1/2024,sidra.khan2024037@sidra.khan2024037@itar.edu.pk,No,30000.0
37,2024038,Shoaib Khan,Male,18,Computer Sci,1,89,89.4,Bannu,5/31/2024,shoaib.khan2024038@shoaib.khan2024038@itar.edu.pk,No,50000.0
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000.0
46,2024047,Kainat Khan,Female,24,IT,8,57,NaN,Bannu,12/17/2024,NaN,Yes,15000.0
54,2024055,Muneeb Khan,Male,25,DS,8,75,NaN,Bannu,8/17/2024,muneeb.khan2024055,Yes,15000.0
57,2024058,Kamran Khan,Male,20,AI,2,40,54.1,Bannu,3/6/2024,kamran.khan2024058,No,30000.0
69,2024070,Haider Khan,Male,20,DS,2,73,83.3,Bannu,9/3/2024,haider.khan2024070@haider.khan2024070@itar.edu.pk,No,30000.0
72,2024073,Sehrish Khan,Female,23,Software Eng,6,86,85.7,Bannu,1/30/2024,sehrish.khan2024073@sehrish.khan2024073@itar.e...,No,30000.0
85,2024086,Awais Ali,Male,19,SE,2,88,84.7,Bannu,10/18/2024,awais.ali2024086,No,30000.0
95,2024096,Yasir Ali,m,21,A I,4,86,92.2,Bannu,9/10/2024,yasir.ali2024096@yasir.ali2024096@itar.edu.pk,Yes,15000.0
97,2024098,Shahzaib Ali,Male,21,IT,3,70,NaN,Bannu,11/25/2024,shahzaib.ali2024098@shahzaib.ali2024098@itar.e...,No,30000.0
105,2024106,Zainab Bibi,Female,25,SE,8,45,NaN,Bannu,3/20/2024,zainab.bibi2024106@zainab.bibi2024106@itar.edu.pk,No,30000.0
107,2024108,Kashif Ali,Male,25,AI,7,84,84.1,Bannu,10/15/2024,NaN,Yes,15000.0
113,2024114,Areeba Bibi,Female,21,A.I,5,81,94.2,Bannu,10/2/2024,areeba.bibi2024114,Yes,15000.0
115,2024116,Shoaib Ali,Male,23,SE,6,97,92.0,Bannu,11/14/2024,shoaib.ali2024116@shoaib.ali2024116@itar.edu.pk,Yes,15000.0
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,30000.0
128,2024129,Naveed Ali,Male,19,SE,2,70,NaN,Bannu,11/20/2024,naveed.ali2024129@naveed.ali2024129@itar.edu.pk,No,30000.0
136,2024137,Farhan Ali,Male,22,CS,4,-10,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,15000.0
137,2024138,Rameez Ali,Male,21,IT,5,67,NaN,Bannu,9/16/2024,rameez.ali2024138@rameez.ali2024138@itar.edu.pk,No,30000.0
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0

##### **Filtering and Selecting Specific Columns**
After filtering rows, we can select only the columns we need from the resulting DataFrame.

In [91]:
df[df["attendance_percentage"] > 92][["full_name", "marks","attendance_percentage"]]

       full_name marks  attendance_percentage
5    Hassan Khan    95                   93.4
20    Yasir Khan    82                   93.7
28   Sohail Khan    81                   94.2
55   Naveed Khan   NaN                   92.2
56    Nimra Khan    87                   94.2
64   Rameez Khan    89                   94.2
75     Hamza Ali    95                   92.1
88     Talha Ali   NaN                   93.4
95     Yasir Ali    86                   92.2
96   Ayesha Bibi    82                   94.9
106    Iqra Bibi    83                  105.0
113  Areeba Bibi    81                   94.2
117    Noor Bibi    94                   92.9
129   Rabia Bibi    86                   94.5
136   Farhan Ali   -10                   94.3
149  Naveed Khan   NaN                   92.2

In [92]:
df.loc[df["attendance_percentage"] > 92, ["full_name", "marks","attendance_percentage"]]

       full_name marks  attendance_percentage
5    Hassan Khan    95                   93.4
20    Yasir Khan    82                   93.7
28   Sohail Khan    81                   94.2
55   Naveed Khan   NaN                   92.2
56    Nimra Khan    87                   94.2
64   Rameez Khan    89                   94.2
75     Hamza Ali    95                   92.1
88     Talha Ali   NaN                   93.4
95     Yasir Ali    86                   92.2
96   Ayesha Bibi    82                   94.9
106    Iqra Bibi    83                  105.0
113  Areeba Bibi    81                   94.2
117    Noor Bibi    94                   92.9
129   Rabia Bibi    86                   94.5
136   Farhan Ali   -10                   94.3
149  Naveed Khan   NaN                   92.2

##### **Filtering with Multiple Conditions**

##### **Filtering Operators**

- `&` means AND
- `|` means OR
- `~` means NOT
- Each condition should normally be enclosed in parentheses.

In [93]:
# CS Students who belong to Bannu City
df[(df["department"] == "CS") & (df["city"] == "Bannu")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000.0
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000.0
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,25000.0
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000.0
136,2024137,Farhan Ali,Male,22,CS,4,-10,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,15000.0

In [94]:
# Students from CS or AI 
df[(df["department"] == "CS") | (df["department"] == "AI")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,15000.0
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,NaN
8,2024009,Usman Khan,Male,22,AI,6,68,64.4,Peshawar,2/23/2024,NaN,No,30000.0
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000.0
16,2024017,Asad Khan,Male,NaN,CS,4,absent,NaN,Kohat,11/22/2024,asad.khan2024017@itar.edu.pk,No,30000.0
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,NaN
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000.0
20,2024021,Yasir Khan,Male,18,CS,2,82,93.7,Kohat,2/12/2024,yasir.khan2024021@yasir.khan2024021@itar.edu.pk,Yes,15000.0
22,2024023,Shahzaib Khan,Male,19,CS,3,74,81.8,Mardan,11/22/2024,shahzaib.khan2024023@shahzaib.khan2024023@itar...,No,30000.0
24,2024025,Rizwan Khan,Male,22,CS,4,46,52.9,Dera Ismail Khan,4/12/2024,rizwan.khan2024025@rizwan.khan2024025@itar.edu.pk,Yes,15000.0
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,25000.0
33,2024034,Waqar Khan,Male,21,AI,5,NaN,91.7,Islamabad,8/3/2024,waqar.khan2024034@waqar.khan2024034@itar.edu.pk,Yes,15000.0
34,2024035,Areeba Khan,Female,24,CS,6,73,83.9,Quetta,12/4/2024,areeba.khan2024035@areeba.khan2024035@itar.edu.pk,No,30000.0
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000.0
43,2024044,Anum Khan,Female,24,CS,6,86,91.9,Swat,11/19/2024,anum.khan2024044,Yes,15000.0
49,2024050,Ahsan Khan,Male,200,AI,7,85,84.2,Mardan,4/25/2024,ahsan.khan2024050@ahsan.khan2024050@itar.edu.pk,No,30000.0
50,2024051,Saba Khan,Female,24,AI,8,86,NaN,Islamabad,1/25/2024,saba.khan2024051,No,30000.0
51,2024052,Maham Khan,Female,22,CS,4,73,86.4,Swat,8/15/2024,maham.khan2024052@maham.khan2024052@itar.edu.pk,Yes,15000.0
53,2024054,Bushra Khan,Female,25,CS,7,90,88.2,Karachi,10/28/2024,bushra.khan2024054@bushra.khan2024054@itar.edu.pk,No,30000.0
55,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0
56,2024057,Nimra Khan,Female,20,CS,3,87,94.2,Swat,7/1/2024,nimra.khan2024057,Yes,15000.0
57,2024058,Kamran Khan,Male,20,AI,2,40,54.1,Bannu,3/6/2024,kamran.khan2024058,No,30000.0
58,2024059,Hafsa Khan,Female,25,AI,8,78,NaN,Islamabad,9/12/2024,hafsa.khan2024059@hafsa.khan2024059@itar.edu.pk,Yes,15000.0
59,2024060,Shakir Khan,Male,18,AI,1,84,92.0,Peshawar,7/31/2024,shakir.khan2024060,No,50000.0
63,2024064,Farhan Khan,Male,21,AI,3,72,86.6,Lahore,2/18/2024,farhan.khan2024064,No,30000.0
64,2024065,Rameez Khan,Male,20,CS,3,89,94.2,Islamabad,2/2/2024,rameez.khan2024065@rameez.khan2024065@itar.edu.pk,Yes,15000.0
65,2024066,Jawad Khan,Male,22,AI,5,88,89.1,Islamabad,6/13/2024,jawad.khan2024066@jawad.khan2024066@itar.edu.pk,No,30000.0
66,2024067,Rehan Khan,Male,NaN,AI,8,NaN,NaN,Kohat,3/18/2024,rehan.khan2024067@rehan.khan2024067@itar.edu.pk,Yes,15000.0
70,2024071,Imran Khan,Male,21,AI,4,80,NaN,Lahore,5/30/2024,imran.khan2024071@imran.khan2024071@itar.edu.pk,No,30000.0
74,2024075,Ahmad Ali,Male,20,CS,2,84,NaN,Peshawar,12/23/2024,ahmad.ali2024075@ahmad.ali2024075@itar.edu.pk,No,30000.0
75,2024076,Hamza Ali,Male,23,AI,6,95,92.1,Islamabad,2/2/2024,NaN,Yes,15000.0
77,2024078,Amna Khan,Female,22,CS,4,NaN,88.8,Lahore,3/23/2024,amna.khan2024078@amna.khan2024078@itar.edu.pk,No,30000.0
78,2024079,Hoorain Khan,Female,19,CS,2,75,NaN,Peshawar,10/28/2024,hoorain.khan2024079@hoorain.khan2024079@itar.e...,No,30000.0
79,2024080,Minal Khan,Female,19,AI,1,71,80.7,Mardan,1/14/2024,minal.khan2024080,No,50000.0
86,2024087,Umar Ali,Male,18,AI,2,81,NaN,Karachi,12/13/2024,umar.ali2024087@umar.ali2024087@itar.edu.pk,No,30000.0
87,2024088,Nida Khan,Female,23,AI,5,80,90.5,Quetta,4/28/2024,nida.khan2024088,No,30000.0
90,2024091,Fahad Ali,male,23,AI,7,78,NaN,Kohat,5/8/2024,fahad.ali2024091@fahad.ali2024091@itar.edu.pk,Yes,15000.0
94,2024095,Fatima Bibi,F,22,CS,6,80,91.4,Peshawar,3/6/2024,fatima.bibi2024095@fatima.bibi2024095@itar.edu.pk,No,30000.0
104,2024105,Sohail Ali,Male,21,CS,3,89,84.8,Karachi,15/03/2024,sohail.ali2024105@sohail.ali2024105@itar.edu.pk,No,30000.0
106,2024107,Iqra Bibi,Female,19,CS,1,83,105.0,Quetta,3/29/2024,iqra.bibi2024107@iqra.bibi2024107@itar.edu.pk,No,50000.0
107,2024108,Kashif Ali,Male,25,AI,7,84,84.1,Bannu,10/15/2024,NaN,Yes,15000.0
109,2024110,Sana Bibi,Female,19,CS,3,96,91.1,Peshawar,2/17/2024,sana.bibi2024110@sana.bibi2024110@itar.edu.pk,Yes,15000.0
114,2024115,Waqar Ali,Male,23,CS,5,81,NaN,Mardan,4/8/2024,waqar.ali2024115,No,30000.0
116,2024117,Irfan Ali,Male,23,CS,7,54,63.6,Mardan,6/2/2024,irfan.ali2024117,No,30000.0
117,2024118,Noor Bibi,Female,23,CS,6,94,92.9,Dera Ismail Khan,6/13/2024,noor.bibi2024118@noor.bibi2024118@itar.edu.pk,Yes,15000.0
119,2024120,Sameer Ali,Male,20,CS,2,61,65.0,Mardan,10/16/2024,sameer.ali2024120@sameer.ali2024120@itar.edu.pk,No,30000.0
120,2024121,Sidra Bibi,Female,18,CS,1,84,89.7,Mardan,3/28/2024,sidra.bibi2024121,No,50000.0
121,2024122,Laiba Bibi,Female,22,AI,4,76,82.9,Mardan,5/5/2024,laiba.bibi2024122@laiba.bibi2024122@itar.edu.pk,Yes,15000.0
127,2024128,Mehwish Bibi,Female,23,CS,5,70,81.9,Dera Ismail Khan,9/20/2024,mehwish.bibi2024128,No,30000.0
130,2024131,Kamran Ali,Male,20,AI,4,78,83.7,Peshawar,12/10/2024,kamran.ali2024131@kamran.ali2024131@itar.edu.pk,Yes,15000.0
131,2024132,Kainat Bibi,Female,19,CS,2,73,NaN,Quetta,6/8/2024,kainat.bibi2024132@kainat.bibi2024132@itar.edu.pk,No,30000.0
136,2024137,Farhan Ali,Male,22,CS,4,-10,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,15000.0
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000.0
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,25000.0
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

In [95]:
# Students Without Scholarships 
df[df["scholarship"] != "Yes"] 
# or 
# df[~(df["scholarship"] == "Yes")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,NaN
7,2024008,Fatima Khan,Female,23,SE,6,70,85.2,Kohat,NaN,fatima.khan2024008@itar.edu.pk,No,30000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,2024143,Asif Ali,Male,21,SE,5,70,NaN,Dera Ismail Khan,Not,asif.ali2024143@asif.ali2024143@itar.edu.pk,No,30000.0
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000.0
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,30000.0

##### **isin()**

`isin()` is useful when checking whether a column value belongs to a list of possible values.

In [96]:
df[df["department"].isin(["DS", "SE"])]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
7,2024008,Fatima Khan,Female,23,SE,6,70,85.2,Kohat,NaN,fatima.khan2024008@itar.edu.pk,No,30000.0
11,2024012,Talha Khan,Male,Nil,SE,4,83,NaN,Islamabad,5/13/2024,talha.khan2024012@itar.edu.pk,Yes,15000.0
12,2024013,Ayesha Khan,Female,24,DS,6,absent,80.5,Mardan,4/8/2024,ayesha.khan2024013@itar.edu.pk,NaN,30000.0
13,2024014,Fahad Khan,Male,18,SE,1,86,82.8,Bannu,3/3/2024,fahad.khan2024014@itar.edu.pk,No,50000.0
15,2024016,Hina Khan,Female,24,DS,8,91,89.3,Dera Ismail Khan,12/7/2024,hina.khan2024016@itar.edu.pk,No,30000.0
17,2024018,Maryam Khan,NaN,22,DS,4,69,84.6,Bannu,2/27/2024,NaN,No,30000.0
23,2024024,Adnan Khan,Male,19,SE,1,82,NaN,Peshawar,10/7/2024,adnan.khan2024024,No,50000.0
28,2024029,Sohail Khan,Male,20,DS,4,81,94.2,Lahore,9/30/2024,sohail.khan2024029@sohail.khan2024029@itar.edu.pk,Yes,15000.0
29,2024030,Kashif Khan,Male,21,SE,4,76,90.5,Bannu,11/25/2024,kashif.khan2024030@kashif.khan2024030@itar.edu.pk,No,30000.0
30,2024031,Komal Khan,Female,25,SE,7,79,NaN,Kohat,8/29/2024,komal.khan2024031@komal.khan2024031@itar.edu.pk,No,30000.0
31,2024032,Salman Khan,Male,23,SE,5,Absent,NaN,Mardan,8/7/2024,salman.khan2024032,No,30000.0
36,2024037,Sidra Khan,Female,23,SE,5,86,82.2,Bannu,12/1/2024,sidra.khan2024037@sidra.khan2024037@itar.edu.pk,No,30000.0
54,2024055,Muneeb Khan,Male,25,DS,8,75,NaN,Bannu,8/17/2024,muneeb.khan2024055,Yes,15000.0
60,2024061,Aamir Khan,Male,NaN,SE,3,83,87.3,Quetta,7/11/2024,aamir.khan2024061,No,30000.0
61,2024062,Rimsha Khan,Female,20,SE,4,70,82.9,Islamabad,4/7/2024,rimsha.khan2024062,No,30000.0
62,2024063,Zeeshan Khan,Male,19,SE,3,98,NaN,Mardan,8/17/2024,zeeshan.khan2024063@zeeshan.khan2024063@itar.e...,Yes,15000.0
69,2024070,Haider Khan,Male,20,DS,2,73,83.3,Bannu,9/3/2024,haider.khan2024070@haider.khan2024070@itar.edu.pk,No,30000.0
76,2024077,Sonia Khan,Female,24,SE,7,76,87.0,Swat,6/25/2024,sonia.khan2024077@sonia.khan2024077@itar.edu.pk,No,30000.0
80,2024081,Fiza Khan,Female,32,SE,5,72,82.4,Peshawar,2/21/2024,fiza.khan2024081,No,30000.0
83,2024084,Bilal Ali,Male,20,SE,2,73,81.5,Mardan,3/28/2024,bilal.ali2024084,Yes,15000.0
85,2024086,Awais Ali,Male,19,SE,2,88,84.7,Bannu,10/18/2024,awais.ali2024086,No,30000.0
88,2024089,Talha Ali,Male,19,DS,2,NaN,93.4,Mardan,12/24/2024,talha.ali2024089@talha.ali2024089@itar.edu.pk,Yes,15000.0
89,2024090,Sahar Khan,Female,18,DS,1,84,87.5,Peshawar,11/22/2024,sahar.khan2024090@sahar.khan2024090@itar.edu.pk,No,50000.0
92,2024093,Asad Ali,M,18,SE,2,87,89.9,Quetta,9/6/2024,asad.ali2024093,Yes,15000.0
99,2024100,Hina Bibi,Female,23,SE,7,73,82.7,Kohat,3/14/2024,hina.bibi2024100,Yes,15000.0
105,2024106,Zainab Bibi,Female,25,SE,8,45,NaN,Bannu,3/20/2024,zainab.bibi2024106@zainab.bibi2024106@itar.edu.pk,No,30000.0
115,2024116,Shoaib Ali,Male,23,SE,6,97,92.0,Bannu,11/14/2024,shoaib.ali2024116@shoaib.ali2024116@itar.edu.pk,Yes,15000.0
118,2024119,Mudassar Ali,Male,19,DS,3,49,NaN,Swat,2/24/2024,mudassar.ali2024119@mudassar.ali2024119@itar.e...,No,30000.0
122,2024123,Usaid Ali,Male,20,DS,3,91,88.8,Peshawar,9/3/2024,usaid.ali2024123@usaid.ali2024123@itar.edu.pk,No,30000.0
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,30000.0
125,2024126,Ahsan Ali,Male,18,DS,1,85,89.6,Islamabad,9/9/2024,ahsan.ali2024126@ahsan.ali2024126@itar.edu.pk,No,50000.0
126,2024127,Muneeb Ali,Male,21,DS,3,74,80.0,Mardan,3/28/2024,muneeb.ali2024127,No,30000.0
128,2024129,Naveed Ali,Male,19,SE,2,70,NaN,Bannu,11/20/2024,naveed.ali2024129@naveed.ali2024129@itar.edu.pk,No,30000.0
129,2024130,Rabia Bibi,Female,20,DS,2,86,94.5,Swat,12/8/2024,rabia.bibi2024130@rabia.bibi2024130@itar.edu.pk,Yes,15000.0
135,2024136,Zeeshan Ali,Male,18,SE,2,73,87.5,Islamabad,3/24/2024,zeeshan.ali2024136@zeeshan.ali2024136@itar.edu.pk,No,30000.0
138,2024139,Jawad Ali,Male,23,DS,7,77,87.2,Kohat,9/11/2024,jawad.ali2024139@jawad.ali2024139@itar.edu.pk,No,30000.0
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,25000.0
140,2024141,Maham Bibi,Female,18,SE,1,82,NaN,Dera Ismail Khan,12/4/2024,maham.bibi2024141,No,50000.0
141,2024142,Rehan Ali,Male,19,DS,3,84,82.1,Peshawar,10/11/2024,rehan.ali2024142@rehan.ali2024142@itar.edu.pk,Yes,15000.0
142,2024143,Asif Ali,Male,21,SE,5,70,NaN,Dera Ismail Khan,Not,asif.ali2024143@asif.ali2024143@itar.edu.pk,No,30000.0

##### **7.2 Sorting**
The `sort_values()` method sorts rows according to one or more columns.

- `ascending=True` sorts from smallest to largest or A to Z.
- `ascending=False` sorts from largest to smallest or Z to A.

In [97]:
# Sort semester in Ascending Order 
df.sort_values(by="semester")

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0
10,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0
9,2024010,Awais Khan,Male,19,IT,1,79,NaN,Islamabad,12/13/2024,awais.khan2024010@itar.edu.pk,No,50000.0
13,2024014,Fahad Khan,Male,18,SE,1,86,82.8,Bannu,3/3/2024,fahad.khan2024014@itar.edu.pk,No,50000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,30000.0
110,2024111,Arslan Ali,Male,19,IT,10,81,82.5,Quetta,9/3/2024,arslan.ali2024111,Yes,NaN
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,NaN
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,NaN

In [98]:
# Sort Semester in Descending Order 
df.sort_values(by="semester", ascending=False)

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,NaN
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,NaN
110,2024111,Arslan Ali,Male,19,IT,10,81,82.5,Quetta,9/3/2024,arslan.ali2024111,Yes,NaN
15,2024016,Hina Khan,Female,24,DS,8,91,89.3,Dera Ismail Khan,12/7/2024,hina.khan2024016@itar.edu.pk,No,30000.0
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,25000.0
140,2024141,Maham Bibi,Female,18,SE,1,82,NaN,Dera Ismail Khan,12/4/2024,maham.bibi2024141,No,50000.0
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,25000.0
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0

In [99]:
# Sort by Department and Semester 
df.sort_values(by=["department", "semester"], ascending=[True, False])

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
95,2024096,Yasir Ali,m,21,A I,4,86,92.2,Bannu,9/10/2024,yasir.ali2024096@yasir.ali2024096@itar.edu.pk,Yes,15000.0
101,2024102,Adeel Ali,Male,20,A I,3,91,NaN,Quetta,8/9/2024,adeel.ali2024102@adeel.ali2024102@itar.edu.pk,Yes,15000.0
113,2024114,Areeba Bibi,Female,21,A.I,5,81,94.2,Bannu,10/2/2024,areeba.bibi2024114,Yes,15000.0
100,2024101,Rizwan Ali,Male,22,A.I.,4,86,88.2,Islamabad,3/23/2024,rizwan.ali2024101@rizwan.ali2024101@itar.edu.pk,Yes,15000.0
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,25000.0
140,2024141,Maham Bibi,Female,18,SE,1,82,NaN,Dera Ismail Khan,12/4/2024,maham.bibi2024141,No,50000.0
26,2024027,Mahnoor Khan,Female,25,Software Eng,7,82,83.3,Mardan,4/7/2024,mahnoor.khan2024027@mahnoor.khan2024027@itar.e...,No,30000.0
72,2024073,Sehrish Khan,Female,23,Software Eng,6,86,85.7,Bannu,1/30/2024,sehrish.khan2024073@sehrish.khan2024073@itar.e...,No,30000.0
48,2024049,Haris Khan,Male,19,cs,1,83,82.7,Mardan,8/28/2024,haris.khan2024049@haris.khan2024049@itar.edu.pk,No,50000.0

#### **8. Rename Columns**

In [100]:
# Rename the marks column to Obtained Marks. 
df.rename(columns={"marks":"Obt_marks"})

,student_id,full_name,gender,age,department,semester,Obt_marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,30000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

In [101]:
# Renaming multiple columns [full_name --> student_name] and [attendance_percentage --> attendance]
df.rename(columns={ 
"full_name":"student_name", 
"attendance_percentage":"attendance" 
})

,student_id,student_name,gender,age,department,semester,marks,attendance,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,50000.0
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,15000.0
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,30000.0
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,15000.0

##### **Checking Whether the Original DataFrame Changed**

When `rename()` is used without `inplace=True`, the original DataFrame is not modified.

The returned DataFrame contains the renamed columns.

In [102]:
df.head()

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0

##### **Creating a Modified DataFrame**

Instead of modifying the original object in place, we can assign the result back to `df`.

This makes the transformation explicit and easier to track.

In [103]:
# To permanently save the changes in the existing DataFrame, use the inplace=True parameter.
# df.rename(columns={"marks":"obt_marks"}, inplace=True)

df_renamed = df.rename(columns={"marks": "obt_marks"})

df_renamed.head()

,student_id,full_name,gender,age,department,semester,obt_marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,15000.0
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,30000.0
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,50000.0
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,30000.0
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,25000.0

#### **9. Adding and Modifying Columns**

A DataFrame allows us to create new columns from existing data.

##### **Converting a Column to Numeric Data**
As here we will use `marks` column for different purposes, but as its data type is str, so we will first convert it into numeric.

The `to_numeric()` function converts values into numeric data types.

Using `errors="coerce"` converts values that cannot be interpreted as numbers into `NaN`.

This is useful when numeric data contains invalid or non-numeric values.

In [104]:
# As we will use marks to use modification, so first we will convert to 'numeric', as it is 'str'
df['marks'] = pd.to_numeric(df['marks'], errors='coerce')

In [105]:
df["bonus_marks"] = 5

df["final_marks"] = df["marks"] + df["bonus_marks"]

df[["full_name", "marks", "bonus_marks", "final_marks"]]

          full_name  marks  bonus_marks  final_marks
0     Muhammad Khan   67.0            5         72.0
1          Ali Khan   77.0            5         82.0
2        Ahmad Khan   70.0            5         75.0
3        Hamza Khan   71.0            5         76.0
4     Abdullah Khan   82.0            5         87.0
..              ...    ...          ...          ...
145      Ahmad Khan   70.0            5         75.0
146  Muhammad Ahmad   80.0            5         85.0
147       Ali Ahmad  105.0            5        110.0
148     Ahmad Ahmad  -10.0            5         -5.0
149     Naveed Khan    NaN            5          NaN

[150 rows x 4 columns]

#### **10. Basic Data Analysis**

##### **10.1 df.count()**
`Purpose:` Counts the total number of values.

`Behavior:` It excludes empty or missing values (NaN).

In [106]:
df["marks"].count()

np.int64(139)

##### **10.2 df.sum()**
`Purpose:` Adds all the numbers together.

`Behavior:` It calculates the grand total of the column.

In [107]:
df["tuition_fee"].sum()

np.float64(3995000.0)

##### **10.3 df.mean()**
`Purpose:` Calculates the average score.

`Behavior:` It divides the sum by the count of values.

In [108]:
df['marks'].mean()

np.float64(77.5251798561151)

##### **10.4 df.median()**

`median()` returns the middle value when the observations are ordered.

If there is an even number of observations, it returns the average of the two middle values.

`Purpose:` Finds the exact middle value.

`Behavior:` It sorts the numbers from lowest to highest and picks the center number.

In [109]:
df['marks'].median()

np.float64(81.0)

##### **10.5 df.min()**
`Purpose:  ` Finds the lowest value.

`Behavior:` It searches for the minimum score in the column.

In [110]:
df['marks'].min()

np.float64(-10.0)

##### **10.6 df.max()**
`Purpose:` Finds the highest value.

`Behavior:` It searches for the maximum score in the column.

In [111]:
df['marks'].max()

np.float64(105.0)

##### **10.7 df.describe()**

The `describe()` method provides a statistical summary of numerical columns, including:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

In [112]:
# do all above at once
df.describe()

,student_id,semester,marks,attendance_percentage,tuition_fee,bonus_marks,final_marks
count,1.500000e+02,150.000000,139.000000,104.000000,147.000000,150.0,139.000000
mean,2.024071e+06,4.366667,77.525180,83.975000,27176.870748,5.0,82.525180
std,4.224882e+01,3.244855,17.948934,14.232915,11119.956564,0.0,17.948934
min,2.024001e+06,1.000000,-10.000000,-5.000000,15000.000000,5.0,-5.000000
25%,2.024035e+06,2.000000,73.000000,82.875000,15000.000000,5.0,78.000000
50%,2.024070e+06,4.000000,81.000000,87.050000,30000.000000,5.0,86.000000
75%,2.024108e+06,6.000000,86.000000,91.125000,30000.000000,5.0,91.000000
max,2.024145e+06,30.000000,105.000000,105.000000,50000.000000,5.0,110.000000

#### **11. Unique Values and Frequency Analysis**

##### **unique()**

Returns the distinct values in a column.

In [113]:
df["city"].unique()

<StringArray>
[           'Bannu',            'Kohat',         'Peshawar',
           'Mardan', 'Dera Ismail Khan',        'Islamabad',
           'Lahore',           'Quetta',             'Swat',
          'Karachi']
Length: 10, dtype: str

##### **nunique()**

Returns the number of distinct values.

In [114]:
df["city"].nunique()

10

##### **value_counts()**

Returns the frequency of each unique value.

In [115]:
df["city"].value_counts()

city
Bannu               29
Mardan              26
Peshawar            20
Kohat               18
Dera Ismail Khan    15
Islamabad           13
Swat                12
Quetta               8
Lahore               5
Karachi              4
Name: count, dtype: int64

> These functions are useful for understanding categorical variables and their frequency distributions.

#### **12. Grouping and Aggregation**

The `groupby()` method allows us to divide data into groups and calculate statistics for each group.

In [116]:
df.groupby("city")["marks"].mean()

city
Bannu               74.642857
Dera Ismail Khan    79.866667
Islamabad           83.000000
Karachi             88.750000
Kohat               79.250000
Lahore              75.500000
Mardan              66.095238
Peshawar            81.300000
Quetta              81.375000
Swat                82.000000
Name: marks, dtype: float64

In [117]:
df.groupby("city")["marks"].agg(["count", "mean", "min", "max"])

                  count       mean   min    max
city
Bannu                28  74.642857 -10.0  105.0
Dera Ismail Khan     15  79.866667  46.0  105.0
Islamabad            12  83.000000  70.0   95.0
Karachi               4  88.750000  81.0   95.0
Kohat                16  79.250000  70.0   91.0
Lahore                4  75.500000  69.0   81.0
Mardan               21  66.095238 -10.0   98.0
Peshawar             20  81.300000  65.0   96.0
Quetta                8  81.375000  73.0   91.0
Swat                 11  82.000000  49.0   96.0

In [118]:
df.groupby("city").agg(
    Average_Marks=("marks", "mean"),
    Average_Attendance=("attendance_percentage", "mean")
)

                  Average_Marks  Average_Attendance
city
Bannu                 74.642857           81.815789
Dera Ismail Khan      79.866667           66.477778
Islamabad             83.000000           88.944444
Karachi               88.750000           87.833333
Kohat                 79.250000           85.880000
Lahore                75.500000           89.866667
Mardan                66.095238           83.057895
Peshawar              81.300000           85.564706
Quetta                81.375000           89.850000
Swat                  82.000000           90.711111

#### **13. Working with Text Data**

Pandas provides the `.str` accessor for applying string operations to an entire Series.

These operations are useful when standardizing and cleaning text data.

In [119]:
# Convert all full_name to Upper Case
df["full_name"].str.upper()

0       MUHAMMAD KHAN
1            ALI KHAN
2          AHMAD KHAN
3          HAMZA KHAN
4       ABDULLAH KHAN
            ...
145        AHMAD KHAN
146    MUHAMMAD AHMAD
147         ALI AHMAD
148       AHMAD AHMAD
149       NAVEED KHAN
Name: full_name, Length: 150, dtype: str

In [120]:
# Convert all full_name to Lower Case
df["full_name"].str.lower()

0       muhammad khan
1            ali khan
2          ahmad khan
3          hamza khan
4       abdullah khan
            ...
145        ahmad khan
146    muhammad ahmad
147         ali ahmad
148       ahmad ahmad
149       naveed khan
Name: full_name, Length: 150, dtype: str

In [122]:
# Delete all spaces before or after the full_name
df["full_name"].str.strip()

0       Muhammad Khan
1            Ali Khan
2          Ahmad Khan
3          Hamza Khan
4       Abdullah Khan
            ...
145        Ahmad Khan
146    Muhammad Ahmad
147         Ali Ahmad
148       Ahmad Ahmad
149       Naveed Khan
Name: full_name, Length: 150, dtype: str

#### **14. Exporting a DataFrame to CSV**

By default, Pandas may write the DataFrame index to the file.

Using `index=False` prevents the index from being saved as an additional column.

In [123]:
df.to_csv("../datasets/cleaned/student_data.csv")

In [125]:
#  Saving a dataframe Without the Index
df.to_csv("../datasets/cleaned/student_data.csv", index=False)

In [126]:
# Select all column and those rows where city is Bannu and save the record in csv file
bannu_city_students = df[df["city"] == "Bannu"]

bannu_city_students.to_csv(
    "../datasets/cleaned/bannu_city_students.csv",
    index=False
)

#### **15. Practical Data Analysis Example**

Let's combine the Pandas concepts learned in this notebook to answer a few questions about student performance.

> Average Marks by Department

In [127]:
df.groupby("department")["marks"].mean()

department
A I             88.500000
A.I             81.000000
A.I.            86.000000
AI              80.772727
CS              75.935484
Computer Sci    89.000000
DS              77.800000
Data Science    89.000000
IT              73.400000
S.E             84.000000
SE              78.520000
Software Eng    84.000000
cs              83.000000
Name: marks, dtype: float64

> Department Performance

In [128]:
df.groupby("department").agg(
    Students=("full_name", "count"),
    Average_Marks=("marks", "mean"),
    Average_Attendance=("attendance_percentage", "mean")
)

              Students  Average_Marks  Average_Attendance
department
A I                  2      88.500000           92.200000
A.I                  1      81.000000           94.200000
A.I.                 1      86.000000           88.200000
AI                  24      80.772727           79.158824
CS                  36      75.935484           86.670370
Computer Sci         1      89.000000           89.400000
DS                  17      77.800000           87.120000
Data Science         2      89.000000           91.500000
IT                  36      73.400000           79.090000
S.E                  1      84.000000           85.200000
SE                  26      78.520000           85.412500
Software Eng         2      84.000000           84.500000
cs                   1      83.000000           82.700000

### **16. Summary**

In this notebook, we learned how to:

- Import Pandas
- Understand Pandas Series
- Understand Pandas DataFrames
- Create DataFrames from dictionaries and NumPy arrays
- Load data from CSV files
- Inspect datasets
- Select rows and columns
- Use `loc[]` and `iloc[]`
- Filter data using conditions
- Use `isin()` for filtering
- Sort DataFrames
- Rename columns
- Add and modify columns
- Convert columns to numeric data types
- Perform basic statistical analysis
- Analyze unique values and frequencies
- Group and aggregate data
- Perform basic text operations
- Export DataFrames to CSV
- Apply Pandas techniques to a practical Data Analysis example

Pandas provides the core data manipulation capabilities required for Data Analysis, Exploratory Data Analysis, Data Science, and Machine Learning workflows.