#### Load Data Set OR Reading Data

In [1]:
import pandas as pd
# Load the dataset 
df = pd.read_csv("../datasets/ITAR_Student_Performance_Dataset_v1.0.csv")
# pd.read_excel("abc.xlsx")
# pd.read_json("data.json")

#### Exploring Data

In [5]:

# Display the first five rows 
df.head()
# print(df.head(10))        # show first 10 rows
# print(df.tail())          # show Last 5 rows
# print(df.tail(8))         # show last 8 rows
# print(df.sample(4))       # show ranndom 4 rows
# df.shape                  # Rows and Columns
# df.columns                # Column Name
# df.index
# df.dtypes                 # Data Types of each column
df.info()                   # Summary Information

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             150 non-null    int64
 1   full_name              150 non-null    str
 2   gender                 148 non-null    str
 3   age                    147 non-null    str
 4   department             150 non-null    str
 5   semester               150 non-null    int64
 6   marks                  142 non-null    str
 7   attendance_percentage  104 non-null    float64
 8   city                   150 non-null    str
 9   admission_date         148 non-null    str
 10  email                  145 non-null    str
 11  scholarship            149 non-null    str
 12  tuition_fee            147 non-null    str
dtypes: float64(1), int64(2), str(10)
memory usage: 15.4 KB

#### Selecting Data

In [3]:
# Display Single Column Data
df["marks"]

0       67.0
1       77.0
2       70.0
3       71.0
4       82.0
       ...
145     70.0
146     80.0
147    105.0
148    -10.0
149      NaN
Name: marks, Length: 150, dtype: float64

In [4]:
# Select Multiple Columns
df[["full_name", "department", "marks"]]

          full_name department  marks
0     Muhammad Khan         SE   67.0
1          Ali Khan         DS   77.0
2        Ahmad Khan         CS   70.0
3        Hamza Khan         DS   71.0
4     Abdullah Khan         AI   82.0
..              ...        ...    ...
145      Ahmad Khan         CS   70.0
146  Muhammad Ahmad         IT   80.0
147       Ali Ahmad         AI  105.0
148     Ahmad Ahmad         IT  -10.0
149     Naveed Khan         CS    NaN

[150 rows x 3 columns]

In [5]:
# Select Multiple Rows
df[1:5]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
1,2024002,Ali Khan,Male,23,DS,6,77.0,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70.0,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71.0,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82.0,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000

> Selecting Data Using loc[]

In [6]:
# Select Single Row
df.loc[0]

student_id                                        2024001
full_name                                   Muhammad Khan
gender                                               Male
age                                                    20
department                                             SE
semester                                                4
marks                                                67.0
attendance_percentage                                80.8
city                                                Bannu
admission_date                                  1/22/2024
email                    muhammad.khan2024001@itar.edu.pk
scholarship                                           Yes
tuition_fee                                         32000
Name: 0, dtype: object

In [7]:
# Select Multiple Rows
df.loc[5:10]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
5,2024006,Hassan Khan,NaN,-5,CS,5,95.0,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,30000
6,2024007,Bilal Khan,Male,22,AI,4,83.0,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,35000
7,2024008,Fatima Khan,Female,23,SE,6,70.0,85.2,Kohat,NaN,fatima.khan2024008@itar.edu.pk,No,32000
8,2024009,Usman Khan,Male,22,AI,6,68.0,64.4,Peshawar,2/23/2024,NaN,No,35000
9,2024010,Awais Khan,Male,19,IT,1,79.0,NaN,Islamabad,12/13/2024,awais.khan2024010@itar.edu.pk,No,28000
10,2024011,Muhammad Ahmad,Male,18,IT,1,80.0,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000

In [ ]:
# Select Multiple Rows and Specific Columns
# df.loc[0:5,"marks"]
df.loc[0:5, ["full_name", "marks"]]

0    67
1    77
2    70
3    71
4    82
5    95
Name: marks, dtype: str

> Selecting Data Using iloc[]

In [9]:
# Select 1st Row
df.iloc[0]

student_id                                        2024001
full_name                                   Muhammad Khan
gender                                               Male
age                                                    20
department                                             SE
semester                                                4
marks                                                67.0
attendance_percentage                                80.8
city                                                Bannu
admission_date                                  1/22/2024
email                    muhammad.khan2024001@itar.edu.pk
scholarship                                           Yes
tuition_fee                                         32000
Name: 0, dtype: object

In [10]:
# Select 1st five rows
df.iloc[0:5]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67.0,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
1,2024002,Ali Khan,Male,23,DS,6,77.0,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70.0,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71.0,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82.0,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000

In [11]:
# Display first five rows and the first four columns. 
df.iloc[0:5, 0:4]

   student_id      full_name gender  age
0     2024001  Muhammad Khan   Male   20
1     2024002       Ali Khan   Male   23
2     2024003     Ahmad Khan   Male   18
3     2024004     Hamza Khan   Male   19
4     2024005  Abdullah Khan   Male   18

> loc[]
* Uses row labels
* Uses column names
* Label-based indexing
* includes both the start and end labels

> iloc[]
* Uses row positions
* Uses column positions
* Integer-based indexing
* follows Python slicing rules and 
excludes the ending position

#### Filter and Sorting Data

> Filtering

In [3]:
# Students with Marks Greater Than 80 
# df[df["marks"] > 80]
df[df["city"]== "Bannu"]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
13,2024014,Fahad Khan,Male,18,SE,1,86,82.8,Bannu,3/3/2024,fahad.khan2024014@itar.edu.pk,No,32000
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000
17,2024018,Maryam Khan,NaN,22,DS,4,69,84.6,Bannu,2/27/2024,NaN,No,34000
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
29,2024030,Kashif Khan,Male,21,SE,4,76,90.5,Bannu,11/25/2024,kashif.khan2024030@kashif.khan2024030@itar.edu.pk,No,32000
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,30000
36,2024037,Sidra Khan,Female,23,SE,5,86,82.2,Bannu,12/1/2024,sidra.khan2024037@sidra.khan2024037@itar.edu.pk,No,32000
37,2024038,Shoaib Khan,Male,18,Computer Sci,1,89,89.4,Bannu,5/31/2024,shoaib.khan2024038@shoaib.khan2024038@itar.edu.pk,No,30000
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000
46,2024047,Kainat Khan,Female,24,IT,8,57,NaN,Bannu,12/17/2024,NaN,Yes,28000
54,2024055,Muneeb Khan,Male,25,DS,8,75,NaN,Bannu,8/17/2024,muneeb.khan2024055,Yes,34000
57,2024058,Kamran Khan,Male,20,AI,2,40,54.1,Bannu,3/6/2024,kamran.khan2024058,No,35000
69,2024070,Haider Khan,Male,20,DS,2,73,83.3,Bannu,9/3/2024,haider.khan2024070@haider.khan2024070@itar.edu.pk,No,34000
72,2024073,Sehrish Khan,Female,23,Software Eng,6,86,85.7,Bannu,1/30/2024,sehrish.khan2024073@sehrish.khan2024073@itar.e...,No,32000
85,2024086,Awais Ali,Male,19,SE,2,88,84.7,Bannu,10/18/2024,awais.ali2024086,No,32000
95,2024096,Yasir Ali,m,21,A I,4,86,92.2,Bannu,9/10/2024,yasir.ali2024096@yasir.ali2024096@itar.edu.pk,Yes,35000
97,2024098,Shahzaib Ali,Male,21,IT,3,70,NaN,Bannu,11/25/2024,shahzaib.ali2024098@shahzaib.ali2024098@itar.e...,No,28000
105,2024106,Zainab Bibi,Female,25,SE,8,45,NaN,Bannu,3/20/2024,zainab.bibi2024106@zainab.bibi2024106@itar.edu.pk,No,32000
107,2024108,Kashif Ali,Male,25,AI,7,84,84.1,Bannu,10/15/2024,NaN,Yes,30000
113,2024114,Areeba Bibi,Female,21,A.I,5,81,94.2,Bannu,10/2/2024,areeba.bibi2024114,Yes,30000
115,2024116,Shoaib Ali,Male,23,SE,6,97,92.0,Bannu,11/14/2024,shoaib.ali2024116@shoaib.ali2024116@itar.edu.pk,Yes,32000
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,32000
128,2024129,Naveed Ali,Male,19,SE,2,70,NaN,Bannu,11/20/2024,naveed.ali2024129@naveed.ali2024129@itar.edu.pk,No,32000
136,2024137,Farhan Ali,Male,22,CS,4,98,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,30000
137,2024138,Rameez Ali,Male,21,IT,5,67,NaN,Bannu,9/16/2024,rameez.ali2024138@rameez.ali2024138@itar.edu.pk,No,28000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000

In [4]:
 # Students from the CS Department 
df[df["department"] == "CS"]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,30000
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000
16,2024017,Asad Khan,Male,NaN,CS,4,absent,NaN,Kohat,11/22/2024,asad.khan2024017@itar.edu.pk,No,30000
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000
20,2024021,Yasir Khan,Male,18,CS,2,82,93.7,Kohat,2/12/2024,yasir.khan2024021@yasir.khan2024021@itar.edu.pk,Yes,30000
22,2024023,Shahzaib Khan,Male,19,CS,3,74,81.8,Mardan,11/22/2024,shahzaib.khan2024023@shahzaib.khan2024023@itar...,No,30000
24,2024025,Rizwan Khan,Male,22,CS,4,46,52.9,Dera Ismail Khan,4/12/2024,rizwan.khan2024025@rizwan.khan2024025@itar.edu.pk,Yes,30000
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,30000
34,2024035,Areeba Khan,Female,24,CS,6,73,83.9,Quetta,12/4/2024,areeba.khan2024035@areeba.khan2024035@itar.edu.pk,No,30000
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000
43,2024044,Anum Khan,Female,24,CS,6,86,91.9,Swat,11/19/2024,anum.khan2024044,Yes,30000
51,2024052,Maham Khan,Female,22,CS,4,73,86.4,Swat,8/15/2024,maham.khan2024052@maham.khan2024052@itar.edu.pk,Yes,30000
53,2024054,Bushra Khan,Female,25,CS,7,90,88.2,Karachi,10/28/2024,bushra.khan2024054@bushra.khan2024054@itar.edu.pk,No,30000
55,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000
56,2024057,Nimra Khan,Female,20,CS,3,87,94.2,Swat,7/1/2024,nimra.khan2024057,Yes,30000
64,2024065,Rameez Khan,Male,20,CS,3,89,94.2,Islamabad,2/2/2024,rameez.khan2024065@rameez.khan2024065@itar.edu.pk,Yes,30000
74,2024075,Ahmad Ali,Male,20,CS,2,84,NaN,Peshawar,12/23/2024,ahmad.ali2024075@ahmad.ali2024075@itar.edu.pk,No,30000
77,2024078,Amna Khan,Female,22,CS,4,NaN,88.8,Lahore,3/23/2024,amna.khan2024078@amna.khan2024078@itar.edu.pk,No,30000
78,2024079,Hoorain Khan,Female,19,CS,2,75,NaN,Peshawar,10/28/2024,hoorain.khan2024079@hoorain.khan2024079@itar.e...,No,30000
94,2024095,Fatima Bibi,F,22,CS,6,80,91.4,Peshawar,3/6/2024,fatima.bibi2024095@fatima.bibi2024095@itar.edu.pk,No,30000
104,2024105,Sohail Ali,Male,21,CS,3,89,84.8,Karachi,15/03/2024,sohail.ali2024105@sohail.ali2024105@itar.edu.pk,No,30000
106,2024107,Iqra Bibi,Female,19,CS,1,83,91.5,Quetta,3/29/2024,iqra.bibi2024107@iqra.bibi2024107@itar.edu.pk,No,"30,000"
109,2024110,Sana Bibi,Female,19,CS,3,96,91.1,Peshawar,2/17/2024,sana.bibi2024110@sana.bibi2024110@itar.edu.pk,Yes,30000
114,2024115,Waqar Ali,Male,23,CS,5,81,NaN,Mardan,4/8/2024,waqar.ali2024115,No,30000
116,2024117,Irfan Ali,Male,23,CS,7,54,63.6,Mardan,6/2/2024,irfan.ali2024117,No,30000
117,2024118,Noor Bibi,Female,23,CS,6,94,92.9,Dera Ismail Khan,6/13/2024,noor.bibi2024118@noor.bibi2024118@itar.edu.pk,Yes,30000
119,2024120,Sameer Ali,Male,20,CS,2,61,65.0,Mardan,10/16/2024,sameer.ali2024120@sameer.ali2024120@itar.edu.pk,No,30000
120,2024121,Sidra Bibi,Female,18,CS,1,84,89.7,Mardan,3/28/2024,sidra.bibi2024121,No,30000
127,2024128,Mehwish Bibi,Female,23,CS,5,70,81.9,Dera Ismail Khan,9/20/2024,mehwish.bibi2024128,No,30000
131,2024132,Kainat Bibi,Female,19,CS,2,73,NaN,Quetta,6/8/2024,kainat.bibi2024132@kainat.bibi2024132@itar.edu.pk,No,30000
136,2024137,Farhan Ali,Male,22,CS,4,98,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,30000
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,30000
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

In [ ]:
# if required specific columns in filter then use

# df[df["attendance_percentage"] > 92][["full_name", "marks","attendance_percentage"]]

df.loc[df["attendance_percentage"] > 92, ["full_name", "marks","attendance_percentage"]]

       full_name marks  attendance_percentage
5    Hassan Khan    95                   93.4
20    Yasir Khan    82                   93.7
28   Sohail Khan    81                   94.2
55   Naveed Khan   NaN                   92.2
56    Nimra Khan    87                   94.2
64   Rameez Khan    89                   94.2
75     Hamza Ali    95                   92.1
88     Talha Ali   NaN                   93.4
95     Yasir Ali    86                   92.2
96   Ayesha Bibi    82                   94.9
113  Areeba Bibi    81                   94.2
117    Noor Bibi    94                   92.9
129   Rabia Bibi    86                   94.5
136   Farhan Ali    98                   94.3
149  Naveed Khan   NaN                   92.2

> Filtering with Multiple Conditions

In [5]:
# CS Students who belong to Bannu City 
df[(df["department"] == "CS") & (df["city"] == "Bannu")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,30000
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000
136,2024137,Farhan Ali,Male,22,CS,4,98,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,30000

In [6]:
# Students from CS or AI 
df[(df["department"] == "CS") | (df["department"] == "AI")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
5,2024006,Hassan Khan,NaN,-5,CS,5,95,93.4,Peshawar,8/3/2024,hassan.khan2024006@itar.edu.pk,Yes,30000
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,35000
8,2024009,Usman Khan,Male,22,AI,6,68,64.4,Peshawar,2/23/2024,NaN,No,35000
14,2024015,Danish Khan,Male,24,CS,8,81,NaN,Bannu,29-7-2024,danish.khan2024015@itar.edu.pk,No,30000
16,2024017,Asad Khan,Male,NaN,CS,4,absent,NaN,Kohat,11/22/2024,asad.khan2024017@itar.edu.pk,No,30000
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,35000
19,2024020,Iqra Khan,Female,24,CS,6,79,NaN,Bannu,4/17/2024,iqra.khan2024020@iqra.khan2024020@itar.edu.pk,No,30000
20,2024021,Yasir Khan,Male,18,CS,2,82,93.7,Kohat,2/12/2024,yasir.khan2024021@yasir.khan2024021@itar.edu.pk,Yes,30000
22,2024023,Shahzaib Khan,Male,19,CS,3,74,81.8,Mardan,11/22/2024,shahzaib.khan2024023@shahzaib.khan2024023@itar...,No,30000
24,2024025,Rizwan Khan,Male,22,CS,4,46,52.9,Dera Ismail Khan,4/12/2024,rizwan.khan2024025@rizwan.khan2024025@itar.edu.pk,Yes,30000
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
32,2024033,Arslan Khan,Male,19,CS,1,81,NaN,Bannu,11/25/2024,arslan.khan2024033@arslan.khan2024033@itar.edu.pk,Yes,30000
33,2024034,Waqar Khan,Male,21,AI,5,NaN,91.7,Islamabad,8/3/2024,waqar.khan2024034@waqar.khan2024034@itar.edu.pk,Yes,35000
34,2024035,Areeba Khan,Female,24,CS,6,73,83.9,Quetta,12/4/2024,areeba.khan2024035@areeba.khan2024035@itar.edu.pk,No,30000
39,2024040,Laiba Khan,Female,25,CS,7,NaN,91.8,Bannu,1/27/2024,laiba.khan2024040@laiba.khan2024040@itar.edu.pk,No,30000
43,2024044,Anum Khan,Female,24,CS,6,86,91.9,Swat,11/19/2024,anum.khan2024044,Yes,30000
49,2024050,Ahsan Khan,Male,23,AI,7,85,84.2,Mardan,4/25/2024,ahsan.khan2024050@ahsan.khan2024050@itar.edu.pk,No,35000
50,2024051,Saba Khan,Female,24,AI,8,86,NaN,Islamabad,1/25/2024,saba.khan2024051,No,35000
51,2024052,Maham Khan,Female,22,CS,4,73,86.4,Swat,8/15/2024,maham.khan2024052@maham.khan2024052@itar.edu.pk,Yes,30000
53,2024054,Bushra Khan,Female,25,CS,7,90,88.2,Karachi,10/28/2024,bushra.khan2024054@bushra.khan2024054@itar.edu.pk,No,30000
55,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000
56,2024057,Nimra Khan,Female,20,CS,3,87,94.2,Swat,7/1/2024,nimra.khan2024057,Yes,30000
57,2024058,Kamran Khan,Male,20,AI,2,40,54.1,Bannu,3/6/2024,kamran.khan2024058,No,35000
58,2024059,Hafsa Khan,Female,25,AI,8,78,NaN,Islamabad,9/12/2024,hafsa.khan2024059@hafsa.khan2024059@itar.edu.pk,Yes,35000
59,2024060,Shakir Khan,Male,18,AI,1,84,92.0,Peshawar,7/31/2024,shakir.khan2024060,No,35000
63,2024064,Farhan Khan,Male,21,AI,3,72,86.6,Lahore,2/18/2024,farhan.khan2024064,No,35000
64,2024065,Rameez Khan,Male,20,CS,3,89,94.2,Islamabad,2/2/2024,rameez.khan2024065@rameez.khan2024065@itar.edu.pk,Yes,30000
65,2024066,Jawad Khan,Male,22,AI,5,88,89.1,Islamabad,6/13/2024,jawad.khan2024066@jawad.khan2024066@itar.edu.pk,No,35000
66,2024067,Rehan Khan,Male,NaN,AI,8,NaN,NaN,Kohat,3/18/2024,rehan.khan2024067@rehan.khan2024067@itar.edu.pk,Yes,35000
70,2024071,Imran Khan,Male,21,AI,4,80,NaN,Lahore,5/30/2024,imran.khan2024071@imran.khan2024071@itar.edu.pk,No,35000
74,2024075,Ahmad Ali,Male,20,CS,2,84,NaN,Peshawar,12/23/2024,ahmad.ali2024075@ahmad.ali2024075@itar.edu.pk,No,30000
75,2024076,Hamza Ali,Male,23,AI,6,95,92.1,Islamabad,2/2/2024,NaN,Yes,35000
77,2024078,Amna Khan,Female,22,CS,4,NaN,88.8,Lahore,3/23/2024,amna.khan2024078@amna.khan2024078@itar.edu.pk,No,30000
78,2024079,Hoorain Khan,Female,19,CS,2,75,NaN,Peshawar,10/28/2024,hoorain.khan2024079@hoorain.khan2024079@itar.e...,No,30000
79,2024080,Minal Khan,Female,19,AI,1,71,80.7,Mardan,1/14/2024,minal.khan2024080,No,35000
86,2024087,Umar Ali,Male,18,AI,2,81,NaN,Karachi,12/13/2024,umar.ali2024087@umar.ali2024087@itar.edu.pk,No,35000
87,2024088,Nida Khan,Female,23,AI,5,80,90.5,Quetta,4/28/2024,nida.khan2024088,No,35000
90,2024091,Fahad Ali,male,23,AI,7,78,NaN,Kohat,5/8/2024,fahad.ali2024091@fahad.ali2024091@itar.edu.pk,Yes,35000
94,2024095,Fatima Bibi,F,22,CS,6,80,91.4,Peshawar,3/6/2024,fatima.bibi2024095@fatima.bibi2024095@itar.edu.pk,No,30000
104,2024105,Sohail Ali,Male,21,CS,3,89,84.8,Karachi,15/03/2024,sohail.ali2024105@sohail.ali2024105@itar.edu.pk,No,30000
106,2024107,Iqra Bibi,Female,19,CS,1,83,91.5,Quetta,3/29/2024,iqra.bibi2024107@iqra.bibi2024107@itar.edu.pk,No,"30,000"
107,2024108,Kashif Ali,Male,25,AI,7,84,84.1,Bannu,10/15/2024,NaN,Yes,30000
109,2024110,Sana Bibi,Female,19,CS,3,96,91.1,Peshawar,2/17/2024,sana.bibi2024110@sana.bibi2024110@itar.edu.pk,Yes,30000
114,2024115,Waqar Ali,Male,23,CS,5,81,NaN,Mardan,4/8/2024,waqar.ali2024115,No,30000
116,2024117,Irfan Ali,Male,23,CS,7,54,63.6,Mardan,6/2/2024,irfan.ali2024117,No,30000
117,2024118,Noor Bibi,Female,23,CS,6,94,92.9,Dera Ismail Khan,6/13/2024,noor.bibi2024118@noor.bibi2024118@itar.edu.pk,Yes,30000
119,2024120,Sameer Ali,Male,20,CS,2,61,65.0,Mardan,10/16/2024,sameer.ali2024120@sameer.ali2024120@itar.edu.pk,No,30000
120,2024121,Sidra Bibi,Female,18,CS,1,84,89.7,Mardan,3/28/2024,sidra.bibi2024121,No,30000
121,2024122,Laiba Bibi,Female,22,AI,4,76,82.9,Mardan,5/5/2024,laiba.bibi2024122@laiba.bibi2024122@itar.edu.pk,Yes,35000
127,2024128,Mehwish Bibi,Female,23,CS,5,70,81.9,Dera Ismail Khan,9/20/2024,mehwish.bibi2024128,No,30000
130,2024131,Kamran Ali,Male,20,AI,4,78,83.7,Peshawar,12/10/2024,kamran.ali2024131@kamran.ali2024131@itar.edu.pk,Yes,35000
131,2024132,Kainat Bibi,Female,19,CS,2,73,NaN,Quetta,6/8/2024,kainat.bibi2024132@kainat.bibi2024132@itar.edu.pk,No,30000
136,2024137,Farhan Ali,Male,22,CS,4,98,94.3,Bannu,5/10/2024,farhan.ali2024137,Yes,30000
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,30000
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

In [7]:
# Students Without Scholarships 
df[df["scholarship"] != "Yes"] 
# or 
# df[~(df["scholarship"] == "Yes")]

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,35000
7,2024008,Fatima Khan,Female,23,SE,6,70,85.2,Kohat,NaN,fatima.khan2024008@itar.edu.pk,No,32000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,2024143,Asif Ali,Male,21,SE,5,70,NaN,Dera Ismail Khan,Not,asif.ali2024143@asif.ali2024143@itar.edu.pk,No,32000
143,2024144,Eman Bibi,Female,20,CS,2,69,84.6,Mardan,7/9/2024,eman.bibi2024144,No,30000
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,28000

> Sorting

In [11]:
# Sort Marks in Ascending Order 
df.sort_values(by="semester")

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
10,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
9,2024010,Awais Khan,Male,19,IT,1,79,NaN,Islamabad,12/13/2024,awais.khan2024010@itar.edu.pk,No,28000
13,2024014,Fahad Khan,Male,18,SE,1,86,82.8,Bannu,3/3/2024,fahad.khan2024014@itar.edu.pk,No,32000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
124,2024125,Haris Ali,Male,25,SE,8,86,NaN,Bannu,3/9/2024,haris.ali2024125@haris.ali2024125@itar.edu.pk,No,32000
110,2024111,Arslan Ali,Male,19,IT,10,81,82.5,Quetta,9/3/2024,arslan.ali2024111,Yes,28000
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,35000
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,35000

In [12]:
# Sort Marks in Descending Order 
df.sort_values(by="semester", ascending=False)

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,35000
6,2024007,Bilal Khan,Male,22,AI,15,83,85.5,Dera Ismail Khan,11/4/2024,bilal.khan2024007@itar.edu.pk,No,35000
110,2024111,Arslan Ali,Male,19,IT,10,81,82.5,Quetta,9/3/2024,arslan.ali2024111,Yes,28000
15,2024016,Hina Khan,Female,24,DS,8,91,89.3,Dera Ismail Khan,12/7/2024,hina.khan2024016@itar.edu.pk,No,34000
25,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,32000
140,2024141,Maham Bibi,Female,18,SE,1,82,NaN,Dera Ismail Khan,12/4/2024,maham.bibi2024141,No,32000
144,2024145,Haider Ali,Male,18,CS,1,95,NaN,Dera Ismail Khan,1/8/2024,haider.ali2024145@haider.ali2024145@itar.edu.pk,Yes,30000
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000

In [13]:
# Sort by Department and Marks 
df.sort_values(by=["department", "semester"], ascending=[True, False])

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
95,2024096,Yasir Ali,m,21,A I,4,86,92.2,Bannu,9/10/2024,yasir.ali2024096@yasir.ali2024096@itar.edu.pk,Yes,35000
101,2024102,Adeel Ali,Male,20,A I,3,91,NaN,Quetta,8/9/2024,adeel.ali2024102@adeel.ali2024102@itar.edu.pk,Yes,35000
113,2024114,Areeba Bibi,Female,21,A.I,5,81,94.2,Bannu,10/2/2024,areeba.bibi2024114,Yes,30000
100,2024101,Rizwan Ali,Male,22,A.I.,4,86,88.2,Islamabad,3/23/2024,rizwan.ali2024101@rizwan.ali2024101@itar.edu.pk,Yes,30000
18,2024019,Zainab Khan,Female,150,AI,30,78,81.5,Kohat,NaN,zainab.khan2024019@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2024140,Saba Bibi,Female,19,SE,1,91,87.2,Peshawar,8/4/2024,saba.bibi2024140@saba.bibi2024140@itar.edu.pk,Yes,32000
140,2024141,Maham Bibi,Female,18,SE,1,82,NaN,Dera Ismail Khan,12/4/2024,maham.bibi2024141,No,32000
26,2024027,Mahnoor Khan,Female,25,Software Eng,7,82,83.3,Mardan,4/7/2024,mahnoor.khan2024027@mahnoor.khan2024027@itar.e...,No,32000
72,2024073,Sehrish Khan,Female,23,Software Eng,6,86,85.7,Bannu,1/30/2024,sehrish.khan2024073@sehrish.khan2024073@itar.e...,No,32000
48,2024049,Haris Khan,Male,19,cs,1,83,82.7,Mardan,8/28/2024,haris.khan2024049@haris.khan2024049@itar.edu.pk,No,30000

#### Rename Columns

In [14]:
# Rename the marks column to final_marks. 
df.rename(columns={"marks":"final_marks"})

,student_id,full_name,gender,age,department,semester,final_marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,28000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

In [15]:
# Renaming multiple columns 
df.rename(columns={ 
"full_name":"student_name", 
"attendance_percentage":"attendance" 
})

,student_id,student_name,gender,age,department,semester,marks,attendance,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,28000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

In [6]:
# check the df is parmanently changed or not
df

,student_id,full_name,gender,age,department,semester,marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,28000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

> Permanently renaming columns

In [7]:
# To permanently save the changes in the existing DataFrame, use the inplace=True parameter.
df.rename(columns={"marks":"final_marks"}, inplace=True)

In [8]:
df

,student_id,full_name,gender,age,department,semester,final_marks,attendance_percentage,city,admission_date,email,scholarship,tuition_fee
0,2024001,Muhammad Khan,Male,20,SE,4,67,80.8,Bannu,1/22/2024,muhammad.khan2024001@itar.edu.pk,Yes,32000
1,2024002,Ali Khan,Male,23,DS,6,77,86.6,Kohat,4/30/2024,ali.khan2024002@itar.edu.pk,No,34000
2,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
3,2024004,Hamza Khan,Male,19,DS,2,71,85.2,Bannu,20-03-2024,hamza.khan2024004@itar.edu.pk,No,34000
4,2024005,Abdullah Khan,Male,18,AI,1,82,NaN,Mardan,1/1/2024,abdullah.khan2024005@itar.edu.pk,Yes,35000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2024003,Ahmad Khan,Male,18,CS,1,70,85.1,Peshawar,12/8/2024,ahmad.khan2024003@itar.edu.pk,No,30000
146,2024011,Muhammad Ahmad,Male,18,IT,1,80,NaN,Kohat,5/25/2024,muhammad.ahmad2024011,No,28000
147,2024026,Ali Ahmad,Male,25,AI,8,105,51.3,Bannu,1/25/2024,ali.ahmad2024026@ali.ahmad2024026@itar.edu.pk,Yes,35000
148,2024041,Ahmad Ahmad,Male,25,IT,7,-10,NaN,Mardan,2/23/2024,ahmad.ahmad2024041@ahmad.ahmad2024041@itar.edu.pk,No,28000
149,2024056,Naveed Khan,Male,19,CS,3,NaN,92.2,Mardan,1/8/2024,naveed.khan2024056@naveed.khan2024056@itar.edu.pk,Yes,30000

> Saving a dataframe as a CSV File

In [10]:
df.to_csv("student_data.csv")

In [11]:
#  Saving a dataframe Without the Index
df.to_csv("student_data.csv", index=False)

> Saving the Modified ITAR Dataset

In [12]:
Bannu_City = df[df["city"] == "Bannu"] 
Bannu_City.to_csv("bannu_city_students.csv", index=False)